#anything that is common between every instance goes in this file 
version: "3"
services:
  client:
    container_name: client
    # build:
    #   context: ./client
    #   dockerfile: Dockerfile.dev

    # env_file:
    #   - ./client/.env
