version: "3"
services:
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/client/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NAME=sheen
    # env_file:
    #   - ./client/.env
