version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8080:80"
    env_file:
      - ./client/.env
