version: "3"
services:
  client:
    container_name: client
    #todo I think that the images need to be unique per container 
    image: seanmac11741/riddlesite:latest
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - ./client/.env
