version: "3"
services:
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      # - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
