version: "3"
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/client/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NAME=sheen
    # env_file:
    #   - ./client/.env
